var Promise;

Promise = require("rsvp").Promise;

Promise.prototype.done = function(done) {
  return this.then(done);
};

Promise.prototype.fail = function(fail) {
  return this.then(null, fail);
};

module.exports = function() {
  return new Promise();
};

// ---
// generated by coffee-script 1.9.2
