var key, oldUser, user, value;

user = {
  id: 1,
  name: "yannick"
};

oldUser = {
  role: "lol",
  name: "bob"
};

for (key in oldUser) {
  value = oldUser[key];
  if (!(key in user)) {
    user[key] = value;
  }
}

console.log(user, oldUser);

// ---
// generated by coffee-script 1.9.2
